# Generated by Django 4.0.1 on 2022-02-10 18:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='blogposts\\media\\photos'), upload_to=''),
        ),
    ]
