# Generated by Django 4.0.1 on 2022-02-12 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_alter_blogpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 19, 19, 24, 161808)),
        ),
    ]
