# Generated by Django 4.0.1 on 2022-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_remove_blogpost_date_blogpost_date_of_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
