# Generated by Django 4.0.1 on 2022-02-16 17:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_alter_blogpost_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Blog/static'), upload_to=''),
        ),
    ]
