# Generated by Django 4.0.1 on 2022-02-17 16:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/image'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
